conda create -n roboflow_depthai_env python=3.8
conda activate roboflow_depthai_env
conda install numpy opencv
pip install roboflowoak depthai

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118